# Generated by Django 5.2 on 2025-04-19 11:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_taskcompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetask',
            name='date',
        ),
        migrations.RemoveField(
            model_name='employeetask',
            name='reported_time',
        ),
        migrations.RemoveField(
            model_name='employeetask',
            name='time',
        ),
        migrations.AddField(
            model_name='employeetask',
            name='due_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
