# Generated by Django 5.2 on 2025-04-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
