# Generated by Django 5.2 on 2025-04-21 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_employee_designation_remove_employee_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('target_achieved', models.IntegerField(default=0)),
                ('target_set', models.IntegerField(default=10)),
                ('incentives', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('admissions_worked_on', models.IntegerField(default=0)),
                ('total_admissions', models.IntegerField(default=0)),
                ('admission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Marketing Executive',
                'verbose_name_plural': 'Marketing Executives',
            },
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.RemoveField(
            model_name='employeetask',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Executive', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='Executive', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), (' marketingexecutive', ' MarketingExecutive'), ('student', 'Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='marketingexecutive',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_executive', to=settings.AUTH_USER_MODEL),
        ),
    ]
