# Generated by Django 5.2 on 2025-04-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_employeetask_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
