# Generated by Django 5.2 on 2025-04-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_employeetask_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('marketingexecutive', 'Marketing Executive'), ('student', 'Student')], max_length=20),
        ),
    ]
