# Generated by Django 5.2 on 2025-04-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('marketingexecutive', 'MarketingExecutive'), ('student', 'Student'), ('admin', 'Admin')], max_length=20),
        ),
    ]
