# Generated by Django 5.2 on 2025-04-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('marketing_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marketingexecutive')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('performance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_target', models.IntegerField()),
                ('achieved_target', models.IntegerField()),
                ('marketing_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marketingexecutive')),
            ],
            options={
                'verbose_name': 'Performance Report',
                'verbose_name_plural': 'Performance Reports',
            },
        ),
    ]
