# Generated by Django 5.2 on 2025-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_employeeattendance_loginrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='role',
            field=models.CharField(default='Student', max_length=50),
        ),
    ]
