# Generated by Django 5.2 on 2025-05-13 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_employeetask_user_alter_employeetask_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
