# Generated by Django 5.2 on 2025-05-13 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_employeetask_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
