# Generated by Django 5.2 on 2025-05-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_employeetask_due_date_alter_employeetask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
