# Generated by Django 5.2 on 2025-05-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_course_certificate_provided_course_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
