# Generated by Django 5.2 on 2025-05-15 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_task_location_task_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='employeetask',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='employeetask',
            name='task_description',
        ),
        migrations.AddField(
            model_name='employeetask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeetask',
            name='task_desc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
