# Generated by Django 5.2 on 2025-05-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
