# Generated by Django 5.2 on 2025-05-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_customuser_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
