# Generated by Django 5.2 on 2025-05-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
