# Generated by Django 5.2 on 2025-05-24 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_marketingexecutive_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='student',
        ),
        migrations.AddField(
            model_name='admission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
