# Generated by Django 5.2 on 2025-05-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_admission_student_alter_admission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='user',
        ),
    ]
