# Generated by Django 5.2 on 2025-05-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_centeradmission_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='centeradmission',
            name='centerhead_name',
            field=models.CharField(default='Center Head', max_length=100),
        ),
    ]
