# Generated by Django 5.2 on 2025-05-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('marketingexecutive', 'MarketingExecutive'), ('student', 'Student'), ('centerhead', 'CenterHead'), ('admin', 'Admin'), ('telecallers', 'Telecallers'), ('faculty', 'Faculty'), ('dataentry', 'DataEntry')], max_length=20),
        ),
    ]
