# Generated by Django 5.2 on 2025-05-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_batch_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_fees_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='PerformanceReport',
        ),
    ]
