# Generated by Django 5.2 on 2025-05-27 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_student_total_fees_paid_delete_performancereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
