# Generated by Django 5.2 on 2025-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_batches', to='core.student'),
        ),
    ]
