# Generated by Django 5.2 on 2025-05-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_batch_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='total_fees_paid',
        ),
    ]
