# Generated by Django 5.2 on 2025-05-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_student_total_fees_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_fees_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
