# Generated by Django 5.2 on 2025-05-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_dailyreport_students_absent_alter_dailyreport_batch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='students_Absent',
            new_name='students_absent',
        ),
    ]
